% 该函数是新版GUI界面的测试程序
function NewGUITest
    %% 设定各参数的缺省值
    % 螺旋桨规格
    N_def = 7000;
    VS_def = 5;
    T_def = 0.2;
    Z_def = 3;
    Dp_def = 0.2;
    Hub_flag_def = 1;
    Dh_def = 0.02;
    Duct_flag_def = 1;
    Dd_def = 0.2;
    Cd_def = 0.2;
    % 叶片切面参数
    Nx_def = 10;
    ChordMethod_def = 'CLmax';
    rx_def = [0.2;0.3;0.4;0.5;0.6;0.7;0.8;0.9;0.95;1];
    % 外部环境参数
    
    % 涵道相关参数
    
    % 其他参数与工具
    
    %% GUI元素的参数
    % 字体大小
    zhfontsize = 14;
    subcolumnfontsize = 18;
    numfontsize = 13;
    % 主界面初始高度和宽度
    Windowht = 750;
    Window = 1000;
    %% 主界面中的GUI元素
    % 生成主界面
    Fig_Main = uifigure('position',[5 55 Window Windowht],...
                        'numbertitle','off',...
                        'name','OpenProp');
    % 生成顶部菜单栏
    MenuStrings = {'文件' '设置' '标签页'};
    Menu = zeros(1,length(MenuStrings));
    for index = 1 : length(MenuStrings)
        Menu(index) = uimenu('parent',Fig_Main,...
                             'text',MenuStrings{index});
    end    
    % 生成子工具栏
    FileStrings = {'保存' '另存为' '载入' '运行'};
    FileMenu = zeros(1,length(FileStrings));
    for index = 1 : length(FileStrings)
        FileMenu(index) = uimenu('parent',Menu(1),...
                                 'text',FileStrings{index});
    end
    
    SettingStrings = {'切换语言' '夜晚模式'};
    SettingMenu = zeros(1,length(SettingStrings));
    for index = 1 : length(SettingStrings)
        SettingMenu(index) = uimenu('parent',Menu(2),...
                                    'text',SettingStrings{index});
    end    
    
    TabPageStrings = {'仅进行叶片设计' '研究参数的影响'};
    for index = 1 : length(TabPageStrings)
        TabPageMenu(index) = uimenu('parent',Menu(3),...
                                    'text',TabPageStrings{index},...
                                    'enable','off');
    end    
    % 生成主界面中的标签栏uitabgroup
    Tabs = uitabgroup('parent',Fig_Main,...
                      'position',[0 0 Window Windowht]);
    % 生成Tabs的第一个标签页“仅进行叶片设计”
    SingleDesign = uitab('parent',Tabs,...
                         'title','仅进行叶片设计');
    % 生成Tabs的第二个标签页“研究参数的影响”
    ParametricStudy = uitab('parent',Tabs,...
                            'title','研究参数的影响');
    %% 标签页“仅进行叶片设计”中的GUI元素
    % 生成SingleDesign中的网格空间
    SingleDesignGrid = uigridlayout(SingleDesign,[3 3],...
                                    'columnwidth',{'2x','4x','3x'},...
                                    'rowheight',{'8x','2x','3x'});
    % 螺旋桨规格 Propeller Specification
    Specifications = uipanel('parent',SingleDesignGrid,...
                             'title','螺旋桨规格',...
                             'titleposition','centertop',...
                             'fontsize',subcolumnfontsize,...
                             'fontweight','bold',...
                             'scrollable','off');
    % 叶片切面参数 Blade Design Values
    BladeDesign = uipanel('parent',SingleDesignGrid,...
                          'title','叶片切面参数',...
                          'titleposition','centertop',...
                          'fontsize',subcolumnfontsize,...
                          'fontweight','bold',...
                          'scrollable','on');
    BladeDesign.Layout.Row = [1 2];
    % 外部环境参数 Inflow Profile Values
    Inflow = uipanel('parent',SingleDesignGrid,...
                     'title','外部环境参数',...
                     'titleposition','centertop',...
                     'fontsize',subcolumnfontsize,...
                     'fontweight','bold',...
                     'scrollable','on');
    Inflow.Layout.Row = [1 2];
    % 涵道相关参数 Duct Design Values
    Duct = uipanel('parent',SingleDesignGrid,...
                   'title','涵道相关参数',...
                   'titleposition','centertop',...
                   'fontsize',subcolumnfontsize,...
                   'fontweight','bold',...
                   'scrollable','off');
    Duct.Layout.Row = 2;
    Duct.Layout.Column = 1;
    % 其他参数与工具 Other Desgin Values & Tools
    Tools = uipanel('parent',SingleDesignGrid,...
                    'title','其他参数与工具',...
                    'titleposition','centertop',...
                    'fontsize',subcolumnfontsize,...
                    'fontweight','bold',...
                    'scrollable','off');
    Tools.Layout.Column = [1 2];
    
    %% 标签页“研究参数的影响”中的GUI元素
    % 生成ParametricStudy中的网格
    ParametricStudyGrid = uigridlayout(ParametricStudy,[1 1]);
    Announcement = uilabel(ParametricStudyGrid,...
                           'text','该功能尚未完成，敬请期待',...
                           'horizontalalignment','center',...
                           'verticalalignment','center',...
                           'fontsize',zhfontsize);
                           
    %% 子栏“螺旋桨规格”中的GUI元素
    % 生成Specifications中的网格
    SpecificationsGrid = uigridlayout(Specifications,[4 1],...
                                      'rowheight',{'3x','2x','2x','3x'},...
                                      'columnspacing',5,...
                                      'rowspacing',5,...
                                      'padding',[5 5 5 5],...
                                      'scrollable','off');   
    % GUI元素
    SpecificationsStrings = {'电机转速','行进速度','总升力','叶片数量','叶片直径','桨毂直径','涵道直径','涵道弦长'};
    SpecificationsTips = {'N','VS','T','Z','Dp','Dh','Dd','Cd'};
    SpecificationsValues_def = {N_def,VS_def,T_def,Z_def,Dp_def,Dh_def,Dd_def,Cd_def};
    % 装置面板
    DevicePanel = uipanel(SpecificationsGrid);
    DevicePanelGrid = uigridlayout(DevicePanel,[3 2],...
                                   'columnwidth',{'2x','3x'},...
                                   'columnspacing',5,...
                                   'rowspacing',5,...
                                   'padding',[5 5 5 5]);    
    for index = 1 : 3
        SpecificationsTexts(index) = uilabel('parent',DevicePanelGrid,...
                                             'text',SpecificationsStrings{index},...
                                             'horizontalalignment','left',...
                                             'verticalalignment','center',...
                                             'tooltip',SpecificationsTips{index},...
                                             'fontsize',zhfontsize);

        SpecificationsValues(index) = uieditfield(DevicePanelGrid,'numeric',...
                                                  'fontsize',numfontsize,...
                                                  'horizontalalignment','center',...
                                                  'value',SpecificationsValues_def{index},...
                                                  'limit',[0 Inf],...
                                                  'lowerlimitinclusive','off');
    end    
    
    % 叶片面板
    BladePanel = uipanel(SpecificationsGrid);
    BladePanelGrid = uigridlayout(BladePanel,[2 2],...
                                  'columnwidth',{'2x','3x'},...
                                  'columnspacing',5,...
                                  'rowspacing',5,...
                                  'padding',[5 5 5 5]);  
    for index = 4 : 5
        SpecificationsTexts(index) = uilabel('parent',BladePanelGrid,...
                                             'text',SpecificationsStrings{index},...
                                             'horizontalalignment','left',...
                                             'verticalalignment','center',...
                                             'tooltip',SpecificationsTips{index},...
                                             'fontsize',zhfontsize);

        SpecificationsValues(index) = uieditfield(BladePanelGrid,'numeric',...
                                                  'fontsize',numfontsize,...
                                                  'horizontalalignment','center',...
                                                  'value',SpecificationsValues_def{index},...
                                                  'limit',[0 Inf],...
                                                  'lowerlimitinclusive','off');
    end    
    
    % 桨毂面板
    HubPanel = uipanel(SpecificationsGrid);
    HubPanelGrid = uigridlayout(HubPanel,[2 2],...
                                'columnwidth',{'2x','3x'},...
                                'columnspacing',5,...
                                'rowspacing',5,...
                                'padding',[5 5 5 5]);  
    FlagsValues(1) = uicheckbox('parent',HubPanelGrid,...
                                'text','是否考虑桨毂？',...
                                'value',Hub_flag_def,...
                                'tooltip','勾选后设计时将考虑桨毂',...
                                'fontsize',zhfontsize);
    FlagsValues(1).Layout.Column = [1 2];
    SpecificationsTexts(6) = uilabel('parent',HubPanelGrid,...
                                     'text',SpecificationsStrings{index},...
                                     'horizontalalignment','left',...
                                     'verticalalignment','center',...
                                     'tooltip',SpecificationsTips{index},...
                                     'fontsize',zhfontsize);
    SpecificationsValues(6) = uieditfield(HubPanelGrid,'numeric',...
                                          'fontsize',numfontsize,...
                                          'horizontalalignment','center',...
                                          'value',SpecificationsValues_def{index},...
                                          'limit',[0 Inf],...
                                          'lowerlimitinclusive','off');
    % 涵道面板
    DuctPanel = uipanel(SpecificationsGrid);
    DuctPanelGrid = uigridlayout(DuctPanel,[3 2],...
                                 'columnwidth',{'2x','3x'},...
                                 'columnspacing',5,...
                                 'rowspacing',5,...
                                 'padding',[5 5 5 5]);  
    FlagsValues(2) = uicheckbox('parent',DuctPanelGrid,...
                                'text','是否考虑涵道？',...
                                'value',Duct_flag_def,...
                                'tooltip','勾选后设计时将考虑桨毂',...
                                'fontsize',zhfontsize);
    FlagsValues(2).Layout.Column = [1 2];
    for index = 7 : 8
        SpecificationsTexts(index) = uilabel('parent',DuctPanelGrid,...
                                             'text',SpecificationsStrings{index},...
                                             'horizontalalignment','left',...
                                             'verticalalignment','center',...
                                             'tooltip',SpecificationsTips{index},...
                                             'fontsize',zhfontsize);

        SpecificationsValues(index) = uieditfield(DuctPanelGrid,'numeric',...
                                                  'fontsize',numfontsize,...
                                                  'horizontalalignment','center',...
                                                  'value',SpecificationsValues_def{index},...
                                                  'limit',[0 Inf],...
                                                  'lowerlimitinclusive','off');
    end    
    
    % 设置Specifications编辑框中的显示形式和单位
    set(SpecificationsValues(1),'valuedisplayformat','%.0f RPM');
    set(SpecificationsValues(2),'valuedisplayformat','%.2f m/s');
    set(SpecificationsValues(3),'valuedisplayformat','%.3f N');
    set(SpecificationsValues(4),'valuedisplayformat','%.0f');
    set(SpecificationsValues(5),'valuedisplayformat','%.3f m');
    set(SpecificationsValues(6),'valuedisplayformat','%.3f m');
    set(SpecificationsValues(7),'valuedisplayformat','%.3f m');
    set(SpecificationsValues(8),'valuedisplayformat','%.3f m');
    
    %% 子栏“叶片切面参数”中的GUI元素
    % 生成BladeDesign中的网格
    BladeDesignGrid = uigridlayout(BladeDesign,[2 1],...
                                   'rowheight',{'1x','11x'},...
                                   'columnspacing',5,...
                                   'rowspacing',5,...
                                   'padding',[5 5 5 5],...
                                   'scrollable','off');
    % 属性1面板
    Property1Panel = uipanel(BladeDesignGrid);
    Property1PanelGrid = uigridlayout(Property1Panel,[1 4],...
                                     'columnwidth',{'2x','3x','2x','3x'},...
                                     'columnspacing',5,...
                                     'rowspacing',5,...
                                     'padding',[5 5 5 5]);  
    Property1Texts(1) = uilabel('parent',Property1PanelGrid,...
                                'text','叶片切面数量',...
                                'horizontalalignment','left',...
                                'verticalalignment','center',...
                                'tooltip','该参数控制下方径向位置的数量',...
                                'fontsize',zhfontsize);
    Property1Values(1) = uieditfield(Property1PanelGrid,'numeric',...
                                     'fontsize',numfontsize,...
                                     'horizontalalignment','center',...
                                     'value',Nx_def,...
                                     'limit',[0 Inf],...
                                     'lowerlimitinclusive','off');
    Property1Texts(2) = uilabel('parent',Property1PanelGrid,...
                                'text','切面设计方法',...
                                'horizontalalignment','left',...
                                'verticalalignment','center',...
                                'tooltip','',...
                                'fontsize',zhfontsize);
    Property1Values(2) = uidropdown('parent',Property1PanelGrid,...
                                    'value',ChordMethod_def,...
                                    'items',{'CLmax','ConeyPLL','FAST2011dCTP','FAST2011dVAC','Brizzolara2007'},...
                                    'fontsize',numfontsize);
    % 表格1面板
    Table1Panel = uipanel(BladeDesignGrid,'scrollable','on');
    
    %% 子栏“外部环境参数”中的GUI元素
    
    %% 子栏“涵道相关参数”中的GUI元素
    
    %% 子栏“其他设计参数与工具”中的GUI元素
    
end